main:
  clusterGroupName: datacenter

global:
  pattern: industrial-edge

  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

  imageregistry:
    account: klawrenc
    hostname: quay.io
    type: quay

  git:
    hostname: github.com
    account: klawrenc
    username: klawrenc
    email: klawrenc@redhat.com 
    dev_revision: klawrenc/odfexpansion
